### ISSUE TITLE
BlueprintExtensionsGenerator.cs: IComponentCodeGenerator could not be found.

### ISSUE THREAD

**Issue by geekrelief** [npruehs/Entitas-Blueprints-CSharp#1]
I followed the instructions under Setup by moving the Entitas and Entitas.CodeGenerator to Entitas.Blueprints, and BlueprintExtensionsGenerator can't find IComponentCodeGenerator.  I'm assuming it's because IComponentCodeGenerator is in an Editor folder, but I'm not sure if scripts external to Editor can access Editor scripts. 

I checked the versions of Entitas and Entitas-Blueprints.  What could be going wrong?

**Comment by npruehs** [comment]
@geekrelief: Sorry, the documentation might have been a bit misleading. It was meant for Entitas.Blueprints developers who'd like to open the solution in Visual Studio directly. 

For Unity, just add Entitas and put the additional Entitas.Blueprint folders here:
- **Entitas.Blueprints:** any project folder, e.g. Assets/Libraries/Entitas/Entitas.Blueprints
- **Entitas.Blueprints.Xml:** any project folder, e.g. Assets/Libraries/Entitas/Entitas.Blueprints.Xml
- **Entitas.Blueprints.CodeGenerator:** any editor folder, Assets/Libraries/Entitas/Entitas.Blueprints.CodeGenerator/Editor

See the project structure of the Match-One-Blueprints project for an example:

https://github.com/npruehs/Match-One-Blueprints/tree/develop/Source/Assets/Libraries/Entitas

**Comment by geekrelief** [comment]
Thanks for the link to the Match-One-Blueprints project.  It helped me get set up.

**Comment by geekrelief** [comment]
@npruesh BlueprintExtensionGenerator.cs should be in an Editor folder otherwise IComponentCodeGenerator can't be found.

**Comment by npruehs** [comment]
Yes, that is exactly what stated above :)

**Comment by geekrelief** [comment]
:) Sorry, I should have read more carefully.
